name: JobListings
version: '2.0'
main: net.refractored.joblistings.JobListings
api-version: '1.21'
authors: [refractored]
depend: [Vault]
softdepend:
  - Essentials
  - eco
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0
  - com.j256.ormlite:ormlite-core:5.6
  - com.j256.ormlite:ormlite-jdbc:5.6