name: Release

on:
  push:
    tags:
      - v*

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: gradle shadowjar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JobListings
          path: ./build/libs/JobListings-*.jar

  publish:
    needs: [build-jar]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Linux
        uses: actions/download-artifact@v4
        with:
          path: ./files

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./files/JobListings/JobListings-*.jar
          tag_name: ${{ github.ref }}
          body: |
            # Changelog
            ${{ github.event.release.body }}
            
            This is an automated draft release.
          draft: true
          prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'prerelease') }}